### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
# Pull Request: Update README for MED-O-COACH

## Overview
This PR updates the README file for the MED-O-COACH application, enhancing clarity and providing a comprehensive guide for users on how to utilize the application effectively.

## Changes Made
- Added a detailed **Overview** section explaining the purpose of MED-O-COACH.
- Included a step-by-step guide under **How to Use** to improve user onboarding.
- Expanded the **Problem Statement** to highlight the need for personalized health recommendations.
- Clarified our **Approach** in generating recommendations based on user data.
- Listed out key **Features** of the application for better understanding.
- Highlighted **Special Attributes** that enhance user experience and security.
- Emphasized the **Uniqueness of Idea** to distinguish MED-O-COACH from other health applications.

## Purpose
The purpose of this update is to provide clear and concise documentation for MED-O-COACH users, improving user experience and ensuring they understand how to effectively interact with the application.

## Reviewers
Please review the changes and provide feedback. Your insights are invaluable for ensuring the clarity and effectiveness of our documentation.

## Related Issues
 #17

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@Megh2005  can you review it and merge it .

**Comment by Megh2005** [comment]
yes it is done

**Comment by Megh2005** [comment]
i am closing the issue @Rizvi-Faiz

**Comment by Rizvi-Faiz** [comment]
@Megh2005  can you change the level label the label should not have space it should be "Level3" not "Level 3"

**Comment by Megh2005** [comment]
No it's perfect, I had a talk with the program managers
No need to worry about it

**Pull request merged**
