### PR TITLE
Updated Readme

### LINKED ISSUE #17: Creation of a very good readme file for this repository
# Readme file modification & documentation enhancement

We want someone to change or modify the entire **Readme.md** file. He / She should do all the required stylings. We want a proper readme file having all the sections required i.e contributors guide, star count, issue template etc. everything 
We are going to give a `Level 3` tag along with all required labels 
Interested people should join this discussion giving links to some of the readme files, designed by him / her

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
# Pull Request for Updating README.md

## Title
Update README.md for Med-o-Next Project

## Description
This PR focuses on the complete reconstruction and enhancement of the README.md file for the Med-o-Next project. The following modifications have been made:

- **Key Features Section:** Updated to better reflect the functionalities of the app, including clearer descriptions and formatting improvements.
  
- **Special Attributes Section:** Enhanced with detailed explanations of each attribute to provide better insights into the app's unique selling points.
  
- **Contribution Guide Section:** Beautified the section for clarity and ease of use, ensuring new contributors can easily understand the steps required to contribute effectively.

## Related Issue
Fixes #17 

## Changes Made
- Modified the Key Features section
- Expanded the Special Attributes section with more details
- Beautified the Contribution Guide section

## Checklist
- [x] I have reviewed the code.
- [x] I have updated the documentation.
- [x] I have tested my changes locally.
- [x] This PR does not introduce any breaking changes.

## Screenshots
image
image
image

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@Megh2005  can you review it

**Comment by Rizvi-Faiz** [comment]
@Megh2005 do I have to do for Med-o-Chat branch Med-o-Lens branch also?

**Comment by Megh2005** [comment]
Don't change the commands

**Comment by Megh2005** [comment]
> @Megh2005 do I have to do for Med-o-Chat branch Med-o-Lens branch also?

Yes
That's why it's a level 3 issue.

**Comment by Rizvi-Faiz** [comment]
@Megh2005 the commands are same just i added git add. which is used to stage the file . we do this before we commit

**Comment by Rizvi-Faiz** [comment]
@Megh2005  shall i make two more pull request one for med-o-chat and one for med-o-lens

**Comment by Megh2005** [comment]
Yes
Make sure you add some screenshots of the project Med-o-Lens, after using it. 
Not required for Med-o-Chat

**Comment by Rizvi-Faiz** [comment]
@Megh2005 screenshots of readme file right ??

**Comment by Megh2005** [comment]
No the deployed project
Add those screenshots in the readme 
I am giving you the deployment link of the project Med-o-Lens

**Comment by Rizvi-Faiz** [comment]
@Megh2005  ok

**Comment by Megh2005** [comment]
Create new readme files, style according to the guidelines and send a PR/MR

**Comment by Rizvi-Faiz** [comment]
@Megh2005 other things like contribution detail etc similar to med - o - next ?

**Comment by Megh2005** [comment]
Don't need to add those
Only add

> Overview 

> Problem Statement 

> Our approach 

> Features

> Special attributes 

> Uniqueness of idea

**Comment by Rizvi-Faiz** [comment]
@Megh2005 please add the levels in this pr and the gssoc-ext and hactoberfest
and also that you assigned me cause if you dont add they will not count towards my points
can you please add them

**Pull request merged**
