### PR TITLE
New readme  med o lens

### LINKED ISSUE #17: Creation of a very good readme file for this repository
# Readme file modification & documentation enhancement

We want someone to change or modify the entire **Readme.md** file. He / She should do all the required stylings. We want a proper readme file having all the sections required i.e contributors guide, star count, issue template etc. everything 
We are going to give a `Level 3` tag along with all required labels 
Interested people should join this discussion giving links to some of the readme files, designed by him / her

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
# Pull Request for MED-O-LENS

## Description

This PR adds a comprehensive README file for the MED-O-LENS project. The README includes the following sections:
- **Overview**: An introduction to MED-O-LENS and its purpose.
- **Problem Statement**: Outlines the key challenges addressed by the project.
- **Our Approach**: Describes the AI and machine learning techniques used in prescription analysis.
- **Features**: Lists the main functionalities of the application.
- **Special Attributes**: Highlights integration and real-time processing capabilities.
- **Uniqueness of Idea**: Details what makes MED-O-LENS stand out.
- **Screenshots Section**: Provides placeholders for screenshots showcasing the application.
- **How to Contribute**: Guidelines for developers who want to contribute to the project.

## Type of Change

Please check the type of change your PR introduces:
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist

Please ensure your pull request adheres to the following guidelines:
- [x] I have reviewed the code and confirmed it meets the style guidelines.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate).
- [x] I have included relevant screenshots (if applicable).

## Related Issues

Fixes #17

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@Megh2005  i have made a pull request to med-o-lens please review it .

**Comment by Megh2005** [comment]
A lot of merge conflicts are coming and ut is failing the checks also

**Comment by Rizvi-Faiz** [comment]
@Megh2005  shall merge it to main branch so from there you can put it in med-o-lens branch ?

**Comment by Rizvi-Faiz** [comment]
@Megh2005  what should i do ?

**Comment by Rizvi-Faiz** [comment]
@Megh2005 all checks passed only merge conflict is there
What should i do ?

**Comment by Megh2005** [comment]
Just do one thing
Leave the other things as it is
Just write your readme gile and push it to the branch
Don't rename any filr

**Comment by Megh2005** [comment]
Give a new PR

**Comment by Megh2005** [comment]
I have created a readme, just edit that and send PR

**Pull request closed without merging**
