### PR TITLE
Enhance Target Languages Dropdown UI & Add Voice Response

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
Description: This PR introduces two key enhancements to the Med-O-Lens application

Changes made:
- Redesigned Language Dropdown UI: Improved usability for easier language selection.
- Voice Response Feature: Added voice responses in the selected language for better accessibility and engagement.

Benefits:

- Improved User Experience: Easier navigation and selection.
- Increased Accessibility: Inclusive for users with varying abilities.

Related issue:
#22 

Screenshots:
Image
...

Image
...

Image

### CODE REVIEW

**Comment by Megh2005** [comment]
Send me your GitHub details

**Comment by J-B-Mugundh** [comment]
> Send me your GitHub details

Do u mean my github id?

**Comment by J-B-Mugundh** [comment]
@Megh2005 Hey man! Sorry.. I've merged it with main branch. Shall I revert it back and raise the PR at Med-o-Lens branch?

**Comment by J-B-Mugundh** [comment]
@Megh2005  Is it fine or Could u please revert this?

**Comment by Megh2005** [comment]
Its not only your fault
It's a negligence from my side too. 
I also forgot to check

**Comment by Megh2005** [comment]
Please send another PR
I reverted the old one

**Pull request merged**
