### PR TITLE
Added Admin dashboard

### PR DESCRIPTION
**Pull request by Nkovaturient**
Issue: #111 

**Implemented functionalities related to Verified Health Article Submission Form and Admin Dashboard**

### CODE REVIEW

**Comment by Megh2005** [comment]
Please fix the merge conflicts

**Comment by Nkovaturient** [comment]
> Please fix the merge conflicts

Hello @Megh2005 , many of the folders were deleted..so far I have kept the imp ones and resolved the conflicts. Kindly look into it and make changes as you desire.

**Comment by iSubhamMani** [comment]
> hey there @iSubhamMani @Megh2005 any updates?

Hey we're a little busy. But we will surely get back to you soon

**Comment by Nkovaturient** [comment]
> > hey there @iSubhamMani @Megh2005 any updates?
> 
> Hey we're a little busy. But we will surely get back to you soon

Alright! 🙂

**Pull request merged**
